### ISSUE TITLE
Tunein Radio Plugin will not load favorites even when configured with login credentials

### ISSUE THREAD

**Issue by chadcarr** [brianhornsby/repository.brianhornsby#1]
Tunein radio service has revoked or expired your partnerId, which breaks the HTTP requests to browse the user's presets, even after they have entered the correct username and password. When I substitute "16" for the partnerId (the partnerId for my Squeezebox) my presets work again.

I see you have killed the github repo for this plugin, but it is really great except for this little bug. Thank you for your efforts. Kodi should add it to the main repo. Please let me know if there is anything I can do to help here.

**Comment by brianhornsby** [comment]
https://brianhornsby.com/blog/dmca-takedown-notice.php
